= Installation
:description: SIP3 Installation Guide

== Overview

SIP3 leverages a traditional microservice architecture that makes easy to scale, in the cloud and on-premise.

Having each one of the SIP3 components deployed independently saves you money, time and resources, but it also brings a layer of extra complexity to the deployment process.
To make your life easier the SIP3 team introduced the https://github.com/sip3io/sip3-ansible[`sip3-ansible`] Github project.

By following the traditional Ansible approach, you will be creating an inventory file that describes the SIP3 installation process.
By doing so, you will be able to quickly deploy your project to any infrastructure, regardless of the size and amount of its traffic.

Note: The `sip3-ansible` project requires Ansible version 2.9 or higher

== Basic Installation

In the following section you will find out how to deploy SIP3 to a simple VoIP network, consisting of one FreeSWITCH server, as shown on the diagram below.
`sip3-captain` will be deployed as an agent to the same server. Afterwards, all the SIP3 backend components will be deployed to another server as a monolithic application.

// TODO...

=== Installing `sip3-captain`

// TODO ...

=== Installing SIP3 backend components

// TODO...