= Metrics

:description: SIP3 Metrics.

== Overview

TODO

== Micrometer

TODO

== SIP Metrics

TODO

=== `sip_call_messages`

==== Tags

Default: `src_host`, `dst_host`, `cseq_method`, `method`, `status_code`, `status_type`.
Optional: UDAs assigned within `"sip_message_udf"` endpoint. 

==== Type

Counter

==== Description

Call SIP messages counter.

=== `sip_call_attempts`

Default: `src_host`, `dst_host`, `state`, `expired`, `retransmits`.
Optional: UDAs assigned within `"sip_message_udf"` endpoint.

==== Type

Counter

==== Description

Call attempts.

=== `sip_call_duration`

Default: `src_host`, `dst_host`, `state`, `expired`, `retransmits`.
Optional: UDAs assigned within `"sip_message_udf"` endpoint.

==== Type

Timer

==== Description

Call duration.

=== `sip_call_trying-delay`

==== Tags

Default: `src_host`, `dst_host`, `retransmits`.
Optional: UDAs assigned within `"sip_message_udf"` endpoint. 

==== Type

Timer

==== Description

The time interval between initial `INVITE` message and corresponding `100` response.

=== `sip_call_setup-time`

==== Tags

Default: `src_host`, `dst_host`, `retransmits`.
Optional: UDAs assigned within `"sip_message_udf"` endpoint. 

==== Type

Timer

==== Description

The time interval between initial `INVITE` message and corresponding `18x` response.

=== `sip_call_establish-time`

==== Tags

Default: `src_host`, `dst_host`, `retransmits`.
Optional: UDAs assigned within `"sip_message_udf"` endpoint. 

==== Type

Timer

==== Description

The time interval between initial `INVITE` message and corresponding `200` response.

=== `sip_call_disconnect-time`

==== Tags

Default: `src_host`, `dst_host`, `retransmits`.
Optional: UDAs assigned within `"sip_message_udf"` endpoint. 

==== Type

Timer

==== Description

The time interval between the first `BYE` message and corresponding `200` response.