= Upgrade Guide
:description: SIP3 Upgrade Guide

== Overview

The document describes the steps to upgrade the SIP3 solution to a new version.
These steps are necessary for quick, successful update without negative outcome.

NOTE: We recommend upgrading the SIP3 solution using the configuration described in the `sip3-ansible` project inventory file.
We support an update procedure between subsequent versions.

NOTE: Starting with release `2026.1.1`, we are changing the `sip3-ansible` project.
From now on, each component must be installed using its own Ansible Playbook.
Component configurations will also be stored in their own inventory files.
This improvement will provide a deeper understanding of how components interact within the SIP3 solution and offer greater flexibility and expanded configuration options for your projects.

Since release `2026.1.1` requires to use Java Virtual Machine version 25.
The SIP3 solution begins to use JVM 25 developed by Adoptium (https://adoptium.net/temurin/releases[JRE Eclipse Temurin by Adoptium]),
which we packaged into `sip3-java` package for Linux. This package is required for other SIP3 solution packages.

You should pay attention to checking JAVA_HOME variable in the configuration files.
The file `environment.conf` exists in all application of SIP3 solution. Locations: `/etc/sip3-{application}/environment.conf`
(e.g. '/etc/sip3-salto/environment.conf`).
JAVA_HOME variable should be set to `/opt/sip3-java`.

Example of `environment.conf`:
```
JAVA_HOME=/opt/sip3-java
JAVA_XMS=-Xms512M
JAVA_XMX=-Xmx1024M
JAVA_GC=-XX:+UseG1GC
JAVA_OTHER=
```
