= User-Defined Functions

== Overview

:description: SIP3 User-Defined Functions.

VoIP systems are very generic. Their basic call flow is strictly defined in various RFCs, however there are still a plenty of ways to customize the business logic on behalf of the protocol itself.

Kamailio SIP proxy is one example of such system. It strictly follows RFC 3261. At the same time it gives you a card blanche for modifying each SIP message accordingly to your business logic. That is what makes every Kamailio configuration specific and harder for engineers to properly set granular VoIP monitoring. 

We designed the SIP3 platform with generic VoIP systems in mind. User-Defined Functions (UDFs) let engineers get granular monitoring data, based on various user-defined and service attributes.

At the moment the SIP3 platform lets you write UDFs using Groovy or JavaScript.

== User-Defined Function Base Structure

Each UDF has the following base structure:

++++
<details open>
<summary>Groovy</summary>
++++
[source,groovy]
----
def eventBus = vertx.eventBus()                                 // <1>
eventBus.localConsumer("sip_message_udf", { event ->            // <2>
    // `event.body` is a Map<String, Object>:
    // {
    //  "src_addr" : String,
    //  "src_host" : String (Optional),
    //  "src_port" : Integer,
    //  "dst_addr" : String,
    //  "dst_host" : String (Optional),
    //  "dst_port" : Integer,
    //  "payload" : Map<String, String>,
    //  "attributes" : Map<String, String|Boolean>
    // }
    def packet = event.body()                                   
    
    def sip_message = packet['payload']                         // <3>
    if (sip_message['from'].matches('<sip:100@.*')) {           
        packet['attributes']['robocall'] = true                 // <4>
    }

    event.reply(true)
})
----
++++
</details>
++++

++++
<details>
<summary>JS</summary>
++++
[source,js]
----
var eventBus = vertx.eventBus();                                // <1>
eventBus.localConsumer("sip_message_udf", function (event) {    // <2>
    // `event.body` is a Map<String, Object>:
    // {
    //  "src_addr" : String,
    //  "src_host" : String (Optional),
    //  "src_port" : Integer,
    //  "dst_addr" : String,
    //  "dst_host" : String (Optional),
    //  "dst_port" : Integer,
    //  "payload" : Map<String, String>,
    //  "attributes" : Map<String, String|Boolean>
    // }
    var packet = event.body();                                  
    
    var sip_message = packet['payload'];                        // <3>
    if (sip_message['from'].match('<sip:100@.*')) {             
        packet['attributes']['robocall'] = true;                // <4>
    }

    event.reply(true);
});
----
++++
</details>
++++

<1> Under the hood SIP3 uses https://vertx.io[Vert.x] framework which makes it pretty simple to write code extensions in different languages. If you want to get more details read https://vertx.io/docs/[Vert.x Documentation] first. Otherwise, just copy the code sample above and modify it according to your needs.

<2> `"sip_message_udf"` is an address of the SIP3 UDF endpoint. As an input it receives a SIP3 packet with generic payload represented as a `Map<String, Object>`.

<3> For example, `"sip_message_udf"` endpoint receives as a payload a SIP message represented as a `Map<String, String>` where keys are SIP header names and values are related SIP header values.

<4> `robocall` is an User-Defined Attribute which was assigned to a SIP3 packet. As long as it's assigned it will be automatically populated in `Advanced Search` and in all related `Service Metrics` as a search criteria.

== User-Defined Attributes

As mentioned in the previous section, the main purpose of any SIP3 UDF is assigning `String` or `Boolean` attribute to a SIP3 packet according to its business logic.

We call such attributes User-Defined Attributes (UDAs). UDAs may bring your experience with SIP3 to the next level if you will follow this simple rule:

CAUTION: Always choose attributes with limited amount of possible options otherwise it may affect database performance and cause serious issues. For instance, if you have a mobile application: `operation_system` or `application_version` are examples of good UDAs.

