= Metrics

:description: SIP3 Metrics.

== Overview

Nowadays every DevOps and Service Reliability Engineer is familiar with the link:[Visibility] concept. Often times Visibility starts with the ability of the maintenance team to react immediately on any service disruption. That is why it is very important to design your system having proper monitoring tools in mind. // TODO - Need a better statement backup

This document will get you in touch with the http://micrometer.io/[Micrometer], framework which allows SIP3 to ship metrics to different backends. Also, below you can find a list of all avaialble Service Metrics.

== Micrometer

TODO
- expensive to bring another monitoring tool for the support team;
- we want to give them service metrics whilte utilizing their own backend;
- micrometer is the tool of choice to deliver those metrics to many different backends
- SIP is utilizing Micrometer's metric types

== SIP Metrics

TODO
- list of all available sip metrics, based on RFC - 6076;

=== *sip_call_messages*

==== Tags

Default: `src_host`, `dst_host`, `cseq_method`, `method`, `status_code`, `status_type`.
Optional: UDAs assigned within `"sip_message_udf"` endpoint. 

==== Type

Counter

==== Description

Call SIP messages counter.

=== *sip_call_attempts*

Default: `src_host`, `dst_host`, `state`, `expired`, `retransmits`.
Optional: UDAs assigned within `"sip_message_udf"` endpoint.

==== Type

Counter

==== Description

Call attempts.

=== `sip_call_duration`

Default: `src_host`, `dst_host`, `state`, `expired`, `retransmits`.
Optional: UDAs assigned within `"sip_message_udf"` endpoint.

==== Type

Timer

==== Description

Call duration.

=== `sip_call_trying-delay`

==== Tags

Default: `src_host`, `dst_host`, `retransmits`.
Optional: UDAs assigned within `"sip_message_udf"` endpoint. 

==== Type

Timer

==== Description

The time interval between initial `INVITE` message and corresponding `100` response.

=== `sip_call_setup-time`

==== Tags

Default: `src_host`, `dst_host`, `retransmits`.
Optional: UDAs assigned within `"sip_message_udf"` endpoint. 

==== Type

Timer

==== Description

The time interval between initial `INVITE` message and corresponding `18x` response.

=== `sip_call_establish-time`

==== Tags

Default: `src_host`, `dst_host`, `retransmits`.
Optional: UDAs assigned within `"sip_message_udf"` endpoint. 

==== Type

Timer

==== Description

The time interval between initial `INVITE` message and corresponding `200` response.

=== `sip_call_disconnect-time`

==== Tags

Default: `src_host`, `dst_host`, `retransmits`.
Optional: UDAs assigned within `"sip_message_udf"` endpoint. 

==== Type

Timer

==== Description

The time interval between the first `BYE` message and corresponding `200` response.